version: "0.6.2"

# ruike 多账户配置
discuz_ruike_domain: "https://www.ruike1.com/"
discuz_ruike:
  - username: "username1"
    password: "password1"

  - username: "username2"
    password: "password2"

# hostloc 多账户配置
discuz_hostloc_domain: "https://hostloc.com"
discuz_hostloc:
  - username: "username1"
    password: "password1"

  - username: "username2"
    password: "password2"

# t00ls 多账户配置
# 安全提问
# 0 = 没有安全提问
# 1 = 母亲的名字
# 2 = 爷爷的名字
# 3 = 父亲出生的城市
# 4 = 您其中一位老师的名字
# 5 = 您个人计算机的型号
# 6 = 您最喜欢的餐馆名称
# 7 = 驾驶执照的最后四位数字
t00ls_domain: "https://www.t00ls.com"
t00ls:
  - username: "t00ls_username"
    password: "t00ls_password"
    qesnum: 1
    qan: "t00ls_qan"

  - username: "t00ls_username"
    password: "t00ls_password"
    qesnum: 1
    qan: "t00ls_qan"

threatbook_domain: "https://x.threatbook.com"
threatbook_cookie: ""

# 到期提醒
renewals:
  - type: "VPS"
    domain: "`https://cloud.tencent.com/`"
    expiration_date: "2024-11-18"

  - type: "VPS"
    domain: "`https://cloud.tencent.com/`"
    expiration_date: "2024-05-21"

  - type: "Domain"
    domain: "`https://www.namesilo.com/`"
    expiration_date: "2024-04-24"

  - type: "Voice"
    domain: "`https://voice.google.com/`"
    expiration_date: "2024-12-01"
